/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface TwoColumnsWithHeaders {
        "afterSwipe": () => Promise<void>;
        "beforeSwipe": (enter: boolean, reveal: boolean) => Promise<boolean>;
        "hideContent": () => Promise<void>;
        "lazyLoadContent": () => Promise<void>;
        "revealContent": () => Promise<void>;
    }
}
declare global {
    interface HTMLTwoColumnsWithHeadersElement extends Components.TwoColumnsWithHeaders, HTMLStencilElement {
    }
    var HTMLTwoColumnsWithHeadersElement: {
        prototype: HTMLTwoColumnsWithHeadersElement;
        new (): HTMLTwoColumnsWithHeadersElement;
    };
    interface HTMLElementTagNameMap {
        "two-columns-with-headers": HTMLTwoColumnsWithHeadersElement;
    }
}
declare namespace LocalJSX {
    interface TwoColumnsWithHeaders {
        "onSlideDidLoad"?: (event: CustomEvent<void>) => void;
    }
    interface IntrinsicElements {
        "two-columns-with-headers": TwoColumnsWithHeaders;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "two-columns-with-headers": LocalJSX.TwoColumnsWithHeaders & JSXBase.HTMLAttributes<HTMLTwoColumnsWithHeadersElement>;
        }
    }
}
